// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSession creates a new instance of MockSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSession {
	mock := &MockSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSession is an autogenerated mock type for the Session type
type MockSession struct {
	mock.Mock
}

type MockSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSession) EXPECT() *MockSession_Expecter {
	return &MockSession_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockSession
func (_mock *MockSession) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSession_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSession_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSession_Expecter) Close() *MockSession_Close_Call {
	return &MockSession_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSession_Close_Call) Run(run func()) *MockSession_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSession_Close_Call) Return(err error) *MockSession_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSession_Close_Call) RunAndReturn(run func() error) *MockSession_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CombinedOutput provides a mock function for the type MockSession
func (_mock *MockSession) CombinedOutput(cmd string) ([]byte, error) {
	ret := _mock.Called(cmd)

	if len(ret) == 0 {
		panic("no return value specified for CombinedOutput")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_CombinedOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CombinedOutput'
type MockSession_CombinedOutput_Call struct {
	*mock.Call
}

// CombinedOutput is a helper method to define mock.On call
//   - cmd string
func (_e *MockSession_Expecter) CombinedOutput(cmd interface{}) *MockSession_CombinedOutput_Call {
	return &MockSession_CombinedOutput_Call{Call: _e.mock.On("CombinedOutput", cmd)}
}

func (_c *MockSession_CombinedOutput_Call) Run(run func(cmd string)) *MockSession_CombinedOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSession_CombinedOutput_Call) Return(bytes []byte, err error) *MockSession_CombinedOutput_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockSession_CombinedOutput_Call) RunAndReturn(run func(cmd string) ([]byte, error)) *MockSession_CombinedOutput_Call {
	_c.Call.Return(run)
	return _c
}
