// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fgeck/gorestic-homelab/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Shutdown provides a mock function for the type MockService
func (_mock *MockService) Shutdown(ctx context.Context, cfg models.SSHShutdownConfig) (*models.SSHResult, error) {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 *models.SSHResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SSHShutdownConfig) (*models.SSHResult, error)); ok {
		return returnFunc(ctx, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SSHShutdownConfig) *models.SSHResult); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SSHResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.SSHShutdownConfig) error); ok {
		r1 = returnFunc(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg models.SSHShutdownConfig
func (_e *MockService_Expecter) Shutdown(ctx interface{}, cfg interface{}) *MockService_Shutdown_Call {
	return &MockService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx, cfg)}
}

func (_c *MockService_Shutdown_Call) Run(run func(ctx context.Context, cfg models.SSHShutdownConfig)) *MockService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.SSHShutdownConfig
		if args[1] != nil {
			arg1 = args[1].(models.SSHShutdownConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Shutdown_Call) Return(sSHResult *models.SSHResult, err error) *MockService_Shutdown_Call {
	_c.Call.Return(sSHResult, err)
	return _c
}

func (_c *MockService_Shutdown_Call) RunAndReturn(run func(ctx context.Context, cfg models.SSHShutdownConfig) (*models.SSHResult, error)) *MockService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockService
func (_mock *MockService) TestConnection(ctx context.Context, cfg models.SSHShutdownConfig) (*models.SSHResult, error) {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 *models.SSHResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SSHShutdownConfig) (*models.SSHResult, error)); ok {
		return returnFunc(ctx, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SSHShutdownConfig) *models.SSHResult); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SSHResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.SSHShutdownConfig) error); ok {
		r1 = returnFunc(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockService_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg models.SSHShutdownConfig
func (_e *MockService_Expecter) TestConnection(ctx interface{}, cfg interface{}) *MockService_TestConnection_Call {
	return &MockService_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, cfg)}
}

func (_c *MockService_TestConnection_Call) Run(run func(ctx context.Context, cfg models.SSHShutdownConfig)) *MockService_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.SSHShutdownConfig
		if args[1] != nil {
			arg1 = args[1].(models.SSHShutdownConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_TestConnection_Call) Return(sSHResult *models.SSHResult, err error) *MockService_TestConnection_Call {
	_c.Call.Return(sSHResult, err)
	return _c
}

func (_c *MockService_TestConnection_Call) RunAndReturn(run func(ctx context.Context, cfg models.SSHShutdownConfig) (*models.SSHResult, error)) *MockService_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}
