// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	ssh0 "github.com/fgeck/gorestic-homelab/internal/services/ssh"
	mock "github.com/stretchr/testify/mock"
	"golang.org/x/crypto/ssh"
)

// NewMockClientFactory creates a new instance of MockClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientFactory {
	mock := &MockClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientFactory is an autogenerated mock type for the ClientFactory type
type MockClientFactory struct {
	mock.Mock
}

type MockClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientFactory) EXPECT() *MockClientFactory_Expecter {
	return &MockClientFactory_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function for the type MockClientFactory
func (_mock *MockClientFactory) NewClient(network string, addr string, config *ssh.ClientConfig) (ssh0.Client, error) {
	ret := _mock.Called(network, addr, config)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 ssh0.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *ssh.ClientConfig) (ssh0.Client, error)); ok {
		return returnFunc(network, addr, config)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *ssh.ClientConfig) ssh0.Client); ok {
		r0 = returnFunc(network, addr, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ssh0.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *ssh.ClientConfig) error); ok {
		r1 = returnFunc(network, addr, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientFactory_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type MockClientFactory_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - network string
//   - addr string
//   - config *ssh.ClientConfig
func (_e *MockClientFactory_Expecter) NewClient(network interface{}, addr interface{}, config interface{}) *MockClientFactory_NewClient_Call {
	return &MockClientFactory_NewClient_Call{Call: _e.mock.On("NewClient", network, addr, config)}
}

func (_c *MockClientFactory_NewClient_Call) Run(run func(network string, addr string, config *ssh.ClientConfig)) *MockClientFactory_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *ssh.ClientConfig
		if args[2] != nil {
			arg2 = args[2].(*ssh.ClientConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientFactory_NewClient_Call) Return(client ssh0.Client, err error) *MockClientFactory_NewClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientFactory_NewClient_Call) RunAndReturn(run func(network string, addr string, config *ssh.ClientConfig) (ssh0.Client, error)) *MockClientFactory_NewClient_Call {
	_c.Call.Return(run)
	return _c
}
