// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fgeck/gorestic-homelab/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Dump provides a mock function for the type MockService
func (_mock *MockService) Dump(ctx context.Context, cfg models.PostgresConfig, outputPath string) (*models.PostgresDumpResult, error) {
	ret := _mock.Called(ctx, cfg, outputPath)

	if len(ret) == 0 {
		panic("no return value specified for Dump")
	}

	var r0 *models.PostgresDumpResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.PostgresConfig, string) (*models.PostgresDumpResult, error)); ok {
		return returnFunc(ctx, cfg, outputPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.PostgresConfig, string) *models.PostgresDumpResult); ok {
		r0 = returnFunc(ctx, cfg, outputPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PostgresDumpResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.PostgresConfig, string) error); ok {
		r1 = returnFunc(ctx, cfg, outputPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Dump_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dump'
type MockService_Dump_Call struct {
	*mock.Call
}

// Dump is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg models.PostgresConfig
//   - outputPath string
func (_e *MockService_Expecter) Dump(ctx interface{}, cfg interface{}, outputPath interface{}) *MockService_Dump_Call {
	return &MockService_Dump_Call{Call: _e.mock.On("Dump", ctx, cfg, outputPath)}
}

func (_c *MockService_Dump_Call) Run(run func(ctx context.Context, cfg models.PostgresConfig, outputPath string)) *MockService_Dump_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.PostgresConfig
		if args[1] != nil {
			arg1 = args[1].(models.PostgresConfig)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Dump_Call) Return(postgresDumpResult *models.PostgresDumpResult, err error) *MockService_Dump_Call {
	_c.Call.Return(postgresDumpResult, err)
	return _c
}

func (_c *MockService_Dump_Call) RunAndReturn(run func(ctx context.Context, cfg models.PostgresConfig, outputPath string) (*models.PostgresDumpResult, error)) *MockService_Dump_Call {
	_c.Call.Return(run)
	return _c
}
