// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandExecutor creates a new instance of MockCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandExecutor {
	mock := &MockCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandExecutor is an autogenerated mock type for the CommandExecutor type
type MockCommandExecutor struct {
	mock.Mock
}

type MockCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandExecutor) EXPECT() *MockCommandExecutor_Expecter {
	return &MockCommandExecutor_Expecter{mock: &_m.Mock}
}

// ExecuteWithEnv provides a mock function for the type MockCommandExecutor
func (_mock *MockCommandExecutor) ExecuteWithEnv(ctx context.Context, env []string, outputPath string, name string, args ...string) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, env, outputPath, name, args)
	} else {
		tmpRet = _mock.Called(ctx, env, outputPath, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecuteWithEnv")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string, ...string) error); ok {
		r0 = returnFunc(ctx, env, outputPath, name, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandExecutor_ExecuteWithEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteWithEnv'
type MockCommandExecutor_ExecuteWithEnv_Call struct {
	*mock.Call
}

// ExecuteWithEnv is a helper method to define mock.On call
//   - ctx context.Context
//   - env []string
//   - outputPath string
//   - name string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) ExecuteWithEnv(ctx interface{}, env interface{}, outputPath interface{}, name interface{}, args ...interface{}) *MockCommandExecutor_ExecuteWithEnv_Call {
	return &MockCommandExecutor_ExecuteWithEnv_Call{Call: _e.mock.On("ExecuteWithEnv",
		append([]interface{}{ctx, env, outputPath, name}, args...)...)}
}

func (_c *MockCommandExecutor_ExecuteWithEnv_Call) Run(run func(ctx context.Context, env []string, outputPath string, name string, args ...string)) *MockCommandExecutor_ExecuteWithEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		var variadicArgs []string
		if len(args) > 4 {
			variadicArgs = args[4].([]string)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockCommandExecutor_ExecuteWithEnv_Call) Return(err error) *MockCommandExecutor_ExecuteWithEnv_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandExecutor_ExecuteWithEnv_Call) RunAndReturn(run func(ctx context.Context, env []string, outputPath string, name string, args ...string) error) *MockCommandExecutor_ExecuteWithEnv_Call {
	_c.Call.Return(run)
	return _c
}
