// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fgeck/gorestic-homelab/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Wake provides a mock function for the type MockService
func (_mock *MockService) Wake(ctx context.Context, cfg models.WOLConfig) (*models.WOLResult, error) {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Wake")
	}

	var r0 *models.WOLResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.WOLConfig) (*models.WOLResult, error)); ok {
		return returnFunc(ctx, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.WOLConfig) *models.WOLResult); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WOLResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.WOLConfig) error); ok {
		r1 = returnFunc(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Wake_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wake'
type MockService_Wake_Call struct {
	*mock.Call
}

// Wake is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg models.WOLConfig
func (_e *MockService_Expecter) Wake(ctx interface{}, cfg interface{}) *MockService_Wake_Call {
	return &MockService_Wake_Call{Call: _e.mock.On("Wake", ctx, cfg)}
}

func (_c *MockService_Wake_Call) Run(run func(ctx context.Context, cfg models.WOLConfig)) *MockService_Wake_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.WOLConfig
		if args[1] != nil {
			arg1 = args[1].(models.WOLConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Wake_Call) Return(wOLResult *models.WOLResult, err error) *MockService_Wake_Call {
	_c.Call.Return(wOLResult, err)
	return _c
}

func (_c *MockService_Wake_Call) RunAndReturn(run func(ctx context.Context, cfg models.WOLConfig) (*models.WOLResult, error)) *MockService_Wake_Call {
	_c.Call.Return(run)
	return _c
}
