// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Wake provides a mock function for the type MockClient
func (_mock *MockClient) Wake(broadcastIP string, mac net.HardwareAddr) error {
	ret := _mock.Called(broadcastIP, mac)

	if len(ret) == 0 {
		panic("no return value specified for Wake")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, net.HardwareAddr) error); ok {
		r0 = returnFunc(broadcastIP, mac)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Wake_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wake'
type MockClient_Wake_Call struct {
	*mock.Call
}

// Wake is a helper method to define mock.On call
//   - broadcastIP string
//   - mac net.HardwareAddr
func (_e *MockClient_Expecter) Wake(broadcastIP interface{}, mac interface{}) *MockClient_Wake_Call {
	return &MockClient_Wake_Call{Call: _e.mock.On("Wake", broadcastIP, mac)}
}

func (_c *MockClient_Wake_Call) Run(run func(broadcastIP string, mac net.HardwareAddr)) *MockClient_Wake_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 net.HardwareAddr
		if args[1] != nil {
			arg1 = args[1].(net.HardwareAddr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Wake_Call) Return(err error) *MockClient_Wake_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Wake_Call) RunAndReturn(run func(broadcastIP string, mac net.HardwareAddr) error) *MockClient_Wake_Call {
	_c.Call.Return(run)
	return _c
}
