// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fgeck/gorestic-homelab/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Backup provides a mock function for the type MockService
func (_mock *MockService) Backup(ctx context.Context, cfg models.ResticConfig, settings models.BackupSettings) (*models.BackupResult, error) {
	ret := _mock.Called(ctx, cfg, settings)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 *models.BackupResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ResticConfig, models.BackupSettings) (*models.BackupResult, error)); ok {
		return returnFunc(ctx, cfg, settings)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ResticConfig, models.BackupSettings) *models.BackupResult); ok {
		r0 = returnFunc(ctx, cfg, settings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BackupResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ResticConfig, models.BackupSettings) error); ok {
		r1 = returnFunc(ctx, cfg, settings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type MockService_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg models.ResticConfig
//   - settings models.BackupSettings
func (_e *MockService_Expecter) Backup(ctx interface{}, cfg interface{}, settings interface{}) *MockService_Backup_Call {
	return &MockService_Backup_Call{Call: _e.mock.On("Backup", ctx, cfg, settings)}
}

func (_c *MockService_Backup_Call) Run(run func(ctx context.Context, cfg models.ResticConfig, settings models.BackupSettings)) *MockService_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ResticConfig
		if args[1] != nil {
			arg1 = args[1].(models.ResticConfig)
		}
		var arg2 models.BackupSettings
		if args[2] != nil {
			arg2 = args[2].(models.BackupSettings)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Backup_Call) Return(backupResult *models.BackupResult, err error) *MockService_Backup_Call {
	_c.Call.Return(backupResult, err)
	return _c
}

func (_c *MockService_Backup_Call) RunAndReturn(run func(ctx context.Context, cfg models.ResticConfig, settings models.BackupSettings) (*models.BackupResult, error)) *MockService_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// Check provides a mock function for the type MockService
func (_mock *MockService) Check(ctx context.Context, cfg models.ResticConfig, settings models.CheckSettings) (*models.CheckResult, error) {
	ret := _mock.Called(ctx, cfg, settings)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 *models.CheckResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ResticConfig, models.CheckSettings) (*models.CheckResult, error)); ok {
		return returnFunc(ctx, cfg, settings)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ResticConfig, models.CheckSettings) *models.CheckResult); ok {
		r0 = returnFunc(ctx, cfg, settings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CheckResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ResticConfig, models.CheckSettings) error); ok {
		r1 = returnFunc(ctx, cfg, settings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockService_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg models.ResticConfig
//   - settings models.CheckSettings
func (_e *MockService_Expecter) Check(ctx interface{}, cfg interface{}, settings interface{}) *MockService_Check_Call {
	return &MockService_Check_Call{Call: _e.mock.On("Check", ctx, cfg, settings)}
}

func (_c *MockService_Check_Call) Run(run func(ctx context.Context, cfg models.ResticConfig, settings models.CheckSettings)) *MockService_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ResticConfig
		if args[1] != nil {
			arg1 = args[1].(models.ResticConfig)
		}
		var arg2 models.CheckSettings
		if args[2] != nil {
			arg2 = args[2].(models.CheckSettings)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Check_Call) Return(checkResult *models.CheckResult, err error) *MockService_Check_Call {
	_c.Call.Return(checkResult, err)
	return _c
}

func (_c *MockService_Check_Call) RunAndReturn(run func(ctx context.Context, cfg models.ResticConfig, settings models.CheckSettings) (*models.CheckResult, error)) *MockService_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Forget provides a mock function for the type MockService
func (_mock *MockService) Forget(ctx context.Context, cfg models.ResticConfig, policy models.RetentionPolicy) (*models.ForgetResult, error) {
	ret := _mock.Called(ctx, cfg, policy)

	if len(ret) == 0 {
		panic("no return value specified for Forget")
	}

	var r0 *models.ForgetResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ResticConfig, models.RetentionPolicy) (*models.ForgetResult, error)); ok {
		return returnFunc(ctx, cfg, policy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ResticConfig, models.RetentionPolicy) *models.ForgetResult); ok {
		r0 = returnFunc(ctx, cfg, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ForgetResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ResticConfig, models.RetentionPolicy) error); ok {
		r1 = returnFunc(ctx, cfg, policy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Forget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forget'
type MockService_Forget_Call struct {
	*mock.Call
}

// Forget is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg models.ResticConfig
//   - policy models.RetentionPolicy
func (_e *MockService_Expecter) Forget(ctx interface{}, cfg interface{}, policy interface{}) *MockService_Forget_Call {
	return &MockService_Forget_Call{Call: _e.mock.On("Forget", ctx, cfg, policy)}
}

func (_c *MockService_Forget_Call) Run(run func(ctx context.Context, cfg models.ResticConfig, policy models.RetentionPolicy)) *MockService_Forget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ResticConfig
		if args[1] != nil {
			arg1 = args[1].(models.ResticConfig)
		}
		var arg2 models.RetentionPolicy
		if args[2] != nil {
			arg2 = args[2].(models.RetentionPolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Forget_Call) Return(forgetResult *models.ForgetResult, err error) *MockService_Forget_Call {
	_c.Call.Return(forgetResult, err)
	return _c
}

func (_c *MockService_Forget_Call) RunAndReturn(run func(ctx context.Context, cfg models.ResticConfig, policy models.RetentionPolicy) (*models.ForgetResult, error)) *MockService_Forget_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockService
func (_mock *MockService) Init(ctx context.Context, cfg models.ResticConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ResticConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockService_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg models.ResticConfig
func (_e *MockService_Expecter) Init(ctx interface{}, cfg interface{}) *MockService_Init_Call {
	return &MockService_Init_Call{Call: _e.mock.On("Init", ctx, cfg)}
}

func (_c *MockService_Init_Call) Run(run func(ctx context.Context, cfg models.ResticConfig)) *MockService_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ResticConfig
		if args[1] != nil {
			arg1 = args[1].(models.ResticConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Init_Call) Return(err error) *MockService_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Init_Call) RunAndReturn(run func(ctx context.Context, cfg models.ResticConfig) error) *MockService_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshots provides a mock function for the type MockService
func (_mock *MockService) Snapshots(ctx context.Context, cfg models.ResticConfig) ([]models.Snapshot, error) {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Snapshots")
	}

	var r0 []models.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ResticConfig) ([]models.Snapshot, error)); ok {
		return returnFunc(ctx, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ResticConfig) []models.Snapshot); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ResticConfig) error); ok {
		r1 = returnFunc(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Snapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshots'
type MockService_Snapshots_Call struct {
	*mock.Call
}

// Snapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg models.ResticConfig
func (_e *MockService_Expecter) Snapshots(ctx interface{}, cfg interface{}) *MockService_Snapshots_Call {
	return &MockService_Snapshots_Call{Call: _e.mock.On("Snapshots", ctx, cfg)}
}

func (_c *MockService_Snapshots_Call) Run(run func(ctx context.Context, cfg models.ResticConfig)) *MockService_Snapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ResticConfig
		if args[1] != nil {
			arg1 = args[1].(models.ResticConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Snapshots_Call) Return(snapshots []models.Snapshot, err error) *MockService_Snapshots_Call {
	_c.Call.Return(snapshots, err)
	return _c
}

func (_c *MockService_Snapshots_Call) RunAndReturn(run func(ctx context.Context, cfg models.ResticConfig) ([]models.Snapshot, error)) *MockService_Snapshots_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type MockService
func (_mock *MockService) Unlock(ctx context.Context, cfg models.ResticConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ResticConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockService_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg models.ResticConfig
func (_e *MockService_Expecter) Unlock(ctx interface{}, cfg interface{}) *MockService_Unlock_Call {
	return &MockService_Unlock_Call{Call: _e.mock.On("Unlock", ctx, cfg)}
}

func (_c *MockService_Unlock_Call) Run(run func(ctx context.Context, cfg models.ResticConfig)) *MockService_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ResticConfig
		if args[1] != nil {
			arg1 = args[1].(models.ResticConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Unlock_Call) Return(err error) *MockService_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Unlock_Call) RunAndReturn(run func(ctx context.Context, cfg models.ResticConfig) error) *MockService_Unlock_Call {
	_c.Call.Return(run)
	return _c
}
