// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fgeck/gorestic-homelab/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandExecutor creates a new instance of MockCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandExecutor {
	mock := &MockCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandExecutor is an autogenerated mock type for the CommandExecutor type
type MockCommandExecutor struct {
	mock.Mock
}

type MockCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandExecutor) EXPECT() *MockCommandExecutor_Expecter {
	return &MockCommandExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCommandExecutor
func (_mock *MockCommandExecutor) Execute(ctx context.Context, name string, args ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, name, args)
	} else {
		tmpRet = _mock.Called(ctx, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) ([]byte, error)); ok {
		return returnFunc(ctx, name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) []byte); ok {
		r0 = returnFunc(ctx, name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCommandExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) Execute(ctx interface{}, name interface{}, args ...interface{}) *MockCommandExecutor_Execute_Call {
	return &MockCommandExecutor_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{ctx, name}, args...)...)}
}

func (_c *MockCommandExecutor_Execute_Call) Run(run func(ctx context.Context, name string, args ...string)) *MockCommandExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommandExecutor_Execute_Call) Return(bytes []byte, err error) *MockCommandExecutor_Execute_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCommandExecutor_Execute_Call) RunAndReturn(run func(ctx context.Context, name string, args ...string) ([]byte, error)) *MockCommandExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteWithEnv provides a mock function for the type MockCommandExecutor
func (_mock *MockCommandExecutor) ExecuteWithEnv(ctx context.Context, env []string, name string, args ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, env, name, args)
	} else {
		tmpRet = _mock.Called(ctx, env, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecuteWithEnv")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, ...string) ([]byte, error)); ok {
		return returnFunc(ctx, env, name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, ...string) []byte); ok {
		r0 = returnFunc(ctx, env, name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, string, ...string) error); ok {
		r1 = returnFunc(ctx, env, name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandExecutor_ExecuteWithEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteWithEnv'
type MockCommandExecutor_ExecuteWithEnv_Call struct {
	*mock.Call
}

// ExecuteWithEnv is a helper method to define mock.On call
//   - ctx context.Context
//   - env []string
//   - name string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) ExecuteWithEnv(ctx interface{}, env interface{}, name interface{}, args ...interface{}) *MockCommandExecutor_ExecuteWithEnv_Call {
	return &MockCommandExecutor_ExecuteWithEnv_Call{Call: _e.mock.On("ExecuteWithEnv",
		append([]interface{}{ctx, env, name}, args...)...)}
}

func (_c *MockCommandExecutor_ExecuteWithEnv_Call) Run(run func(ctx context.Context, env []string, name string, args ...string)) *MockCommandExecutor_ExecuteWithEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		var variadicArgs []string
		if len(args) > 3 {
			variadicArgs = args[3].([]string)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCommandExecutor_ExecuteWithEnv_Call) Return(bytes []byte, err error) *MockCommandExecutor_ExecuteWithEnv_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCommandExecutor_ExecuteWithEnv_Call) RunAndReturn(run func(ctx context.Context, env []string, name string, args ...string) ([]byte, error)) *MockCommandExecutor_ExecuteWithEnv_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteWithEnvStreaming provides a mock function for the type MockCommandExecutor
func (_mock *MockCommandExecutor) ExecuteWithEnvStreaming(ctx context.Context, env []string, progressCb models.ResticProgressCallback, name string, args ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, env, progressCb, name, args)
	} else {
		tmpRet = _mock.Called(ctx, env, progressCb, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecuteWithEnvStreaming")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, models.ResticProgressCallback, string, ...string) ([]byte, error)); ok {
		return returnFunc(ctx, env, progressCb, name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, models.ResticProgressCallback, string, ...string) []byte); ok {
		r0 = returnFunc(ctx, env, progressCb, name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, models.ResticProgressCallback, string, ...string) error); ok {
		r1 = returnFunc(ctx, env, progressCb, name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandExecutor_ExecuteWithEnvStreaming_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteWithEnvStreaming'
type MockCommandExecutor_ExecuteWithEnvStreaming_Call struct {
	*mock.Call
}

// ExecuteWithEnvStreaming is a helper method to define mock.On call
//   - ctx context.Context
//   - env []string
//   - progressCb models.ResticProgressCallback
//   - name string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) ExecuteWithEnvStreaming(ctx interface{}, env interface{}, progressCb interface{}, name interface{}, args ...interface{}) *MockCommandExecutor_ExecuteWithEnvStreaming_Call {
	return &MockCommandExecutor_ExecuteWithEnvStreaming_Call{Call: _e.mock.On("ExecuteWithEnvStreaming",
		append([]interface{}{ctx, env, progressCb, name}, args...)...)}
}

func (_c *MockCommandExecutor_ExecuteWithEnvStreaming_Call) Run(run func(ctx context.Context, env []string, progressCb models.ResticProgressCallback, name string, args ...string)) *MockCommandExecutor_ExecuteWithEnvStreaming_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 models.ResticProgressCallback
		if args[2] != nil {
			arg2 = args[2].(models.ResticProgressCallback)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		var variadicArgs []string
		if len(args) > 4 {
			variadicArgs = args[4].([]string)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockCommandExecutor_ExecuteWithEnvStreaming_Call) Return(bytes []byte, err error) *MockCommandExecutor_ExecuteWithEnvStreaming_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCommandExecutor_ExecuteWithEnvStreaming_Call) RunAndReturn(run func(ctx context.Context, env []string, progressCb models.ResticProgressCallback, name string, args ...string) ([]byte, error)) *MockCommandExecutor_ExecuteWithEnvStreaming_Call {
	_c.Call.Return(run)
	return _c
}
